[hotreload]
  suffixes = [".go"]
  ignore = []

[app]
  #app 名称
  name = "budget-api"
  #app url
  url  = "http://192.168.99.1"
  #app 文档地址
  doc = "./apidoc"
  addr = ":80"
  #单元测试调试信息
  debug = false

  [app.logger]
    level = "INFO"
    name = "application"

#数据库驱动
# [database]
#     dirver = "mongodb"

[mongodb]
  # connect = "127.0.0.1:27017"
  connect = "mongodb:27017"
  database = "budget-api"


#reids
[redis]
  Addr = "redis:6379"
  Password = ""
  DB = 0

